force-app/main/default/objects/ORG_Manager__c/ORG_Manager__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ORG_Manager Constant holder</description>
    <label>ORG_Manager</label>
</CustomObject>

force-app/main/default/objects/ORG_Manager__c/fields/Callback_URL__c.field-meta.xml
<CustomField>
    <fullName>Callback_URL__c</fullName>
    <label>Callback URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ORG_Manager__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <description>Blob privateKey= Crypto.generateAesKey(256);
String cryptoKey =EncodingUtil.base64Encode(privateKey);</description>
    <inlineHelpText>one time Generate Private key used in authenticating response.
USE Code From Description</inlineHelpText>
    <label>Private Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ORG_Constant.cls
public class ORG_Constant {

    public static String CONSUMER_KEY{set;get{
        return  ORG_Manager__c.getInstance().Consumer_Key__c;
    }}
    public static String PRIVATE_KEY{set;get{
        return  ORG_Manager__c.getInstance().Private_Key__c;
    }}
    public static String CONSUMER_SECRET{set;get{
        return  ORG_Manager__c.getInstance().Consumer_Secret__c;
    }}
    public static String RETURN_URL{set;get{
        return ORG_Manager__c.getInstance().Callback_URL__c;
    }}
}